# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'car_purchased_or_not.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(576, 519)
        Form.setStyleSheet("color: rgb(170, 170, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 20, 471, 41))
        self.label.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 75 18pt \"Calisto MT\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(50, 110, 81, 31))
        self.label_3.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 16pt \"Calisto MT\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 91, 31))
        self.label_4.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 16pt \"Calisto MT\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 290, 141, 31))
        self.label_5.setStyleSheet("color: rgb(0, 0, 127);\n"
"font: 16pt \"Calisto MT\";")
        self.label_5.setObjectName("label_5")
        self.ResultButton = QtWidgets.QPushButton(Form)
        self.ResultButton.setGeometry(QtCore.QRect(40, 430, 161, 41))
        self.ResultButton.setStyleSheet("color: rgb(170, 170, 255);\n"
"font: 15pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 127);")
        self.ResultButton.setObjectName("ResultButton")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(230, 430, 221, 41))
        self.result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 127);\n"
"font: 75 14pt \"Calisto MT\";")
        self.result.setText("")
        self.result.setObjectName("result")
        self.Gender = QtWidgets.QLineEdit(Form)
        self.Gender.setGeometry(QtCore.QRect(220, 110, 211, 41))
        self.Gender.setStyleSheet("font: 75 14pt \"Calisto MT\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.Gender.setObjectName("Gender")
        self.age = QtWidgets.QLineEdit(Form)
        self.age.setGeometry(QtCore.QRect(220, 190, 211, 41))
        self.age.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Calisto MT\";\n"
"color: rgb(0, 0, 127);")
        self.age.setObjectName("age")
        self.AnnualSalary = QtWidgets.QLineEdit(Form)
        self.AnnualSalary.setGeometry(QtCore.QRect(220, 290, 211, 41))
        self.AnnualSalary.setStyleSheet("color: rgb(0, 0, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 14pt \"Calisto MT\";")
        self.AnnualSalary.setObjectName("AnnualSalary")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 140, 101, 20))
        self.label_6.setStyleSheet("font: 75 12pt \"Calisto MT\";\n"
"color: rgb(0, 0, 127);")
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.ResultButton.raise_()
        self.label_3.raise_()
        self.result.raise_()
        self.Gender.raise_()
        self.age.raise_()
        self.AnnualSalary.raise_()
        self.label_6.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Perdict whether car is purchased or not"))
        self.label_3.setText(_translate("Form", "Gender  "))
        self.label_4.setText(_translate("Form", "Age"))
        self.label_5.setText(_translate("Form", "AnnualSalary"))
        self.ResultButton.setText(_translate("Form", "Predict"))
        self.label_6.setText(_translate("Form", "(male , female)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
